"""
Chunked HTML -> NKG JSON extractor (Cypher-ready)

Purpose
-------
- Process ONE cleaned HTML page at a time.
- Send HTML in chunks to Ollama (gemma4:31b by default) to improve extraction accuracy.
- Merge chunk outputs into a single page-level NKG.
- Verify DOM ids from HTML are covered in extracted elements.
- Export JSON that is directly usable as Cypher parameters.
- Support one-shot prompting via `--one-shot-example`.

Example
-------
python prompting_chunk/chunked_html_to_nkg.py --html data/cleaned_html/customer_employee.html --out data/nkg_chunked_output/customer_employee.nkg.json --model gemma4:31b --stream

Then reuse as one-shot example:
python prompting_chunk/chunked_html_to_nkg.py --html data/cleaned_html/customer_attendance_leave.html --one-shot-example data/nkg_chunked_output/customer_employee.nkg.json --out data/nkg_chunked_output/customer_attendance_leave.nkg.json --model gemma4:31b --stream
"""

from __future__ import annotations

import argparse
from contextlib import redirect_stderr, redirect_stdout
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
import os
import re
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib import error, request

try:
    from bs4 import BeautifulSoup
except ImportError:
    BeautifulSoup = None


DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_REMOTE_SERVER_URL = "https://youtube.com"
DEFAULT_REMOTE_API_TOKEN = "some-secret-token"
DEFAULT_MODEL = "gemma4:31b"
DEFAULT_TIMEOUT = 600


CHUNK_SYSTEM_PROMPT = """You are an expert UI analyst building a Navigational Knowledge Graph (NKG) for an HR SaaS admin panel.

You are processing ONLY ONE HTML CHUNK from a page.
Return ONLY a valid JSON object (no markdown, no explanation, no extra wrapper keys).

Rules:
1) Capture user-relevant UI elements, not only clickable controls.
2) If an element has DOM id, NKG id must be exactly that DOM id.
3) For id elements, selector must be exactly '#<id>'.
4) For no-id elements, generate snake_case id prefixed with '<page_slug>__'.
5) Descriptions must be in Bahasa Indonesia and rich enough for semantic search: specific, concrete, and grounded in the visible text, purpose, state, and surrounding context.
6) to_type:
    - 'element' for same-page reveal/open interaction.
    - 'page' for route/url change.
7) Hidden/show patterns are important. If likely, add trigger from control -> hidden target.
8) Include explanatory, contextual, or status elements when they help the user understand what a page/field/section means.
9) Do not output decorative-only or structural wrapper elements.
10) If unsure for a no-id element, include it if it is likely user-relevant.
11) If a user-relevant element is clearly nested under another user-relevant element, set parent_element_id.

Schema:
{
  "page": {"id": "/customer/<route>", "title": "...", "desc": "..."},
  "elements": [
        {"id": "...", "desc": "...", "type": "button|input|select|textarea|modal|table|link|tab|section", "selector": "...", "parent_element_id": "optional_parent_id"}
  ],
  "triggers": [
    {"from": "...", "to": "element_id_or_/page/path", "to_type": "element|page"}
  ]
}
"""


PATCH_SYSTEM_PROMPT = """You are fixing an EXISTING page-level NKG by INSERTION ONLY.
Return ONLY valid JSON (no markdown, no explanation).

Rules:
1) Review each id in MISSING_DOM_IDS and decide if it is user-relevant for NKG (interactive, explanatory, contextual, or status-bearing) or should be excluded as noise.
2) Keep each id exactly verbatim as DOM id.
3) For included DOM-id elements, selector must be exactly '#<id>'.
4) Exclude decorative/system/noise ids (example: autogenerated select2 data ids, purely presentational wrappers) unless clearly actionable.
5) Add triggers only when confident and relevant.
6) Never remove existing elements/triggers.

Schema:
{
  "elements": [
        {"id": "...", "desc": "...", "type": "button|input|select|textarea|modal|table|link|tab|section", "selector": "#...", "parent_element_id": "optional_parent_id"}
  ],
    "excluded": [
                {"id": "...", "reason": "alasan singkat kenapa tidak layak dimasukkan"}
    ],
  "triggers": [
    {"from": "...", "to": "element_id_or_/page/path", "to_type": "element|page"}
  ]
}
"""


GLOBAL_RECONCILE_SYSTEM_PROMPT = """You are reconciling a page-level NKG after chunked extraction.
Return ONLY a valid JSON object using this PATCH schema:
{
    "elements": [
        {"id": "...", "desc": "...", "type": "button|input|select|textarea|modal|table|link|tab|section", "selector": "...", "parent_element_id": "optional_parent_id"}
    ],
    "triggers": [
        {"from": "...", "to": "...", "to_type": "element|page"}
    ]
}

Critical goals:
1) Focus on relationships that can be missed by chunk boundaries.
2) Add only useful INSERTIONS/UPDATES; do not regenerate full page-level NKG.
3) Keep DOM id elements with selector '#id'.
4) Add parent_element_id when an element is clearly nested inside another user-relevant element (e.g. form fields inside modal).
5) Avoid duplicates and avoid decorative-only noise.
6) Prefer descriptions that are informative enough for later semantic retrieval: mention what the UI shows, what it is for, and any important state or scope.
"""


SELECTOR_REPAIR_SYSTEM_PROMPT = """You are repairing CSS selectors for existing NKG elements.
Return ONLY valid JSON (no markdown, no explanation).

Rules:
1) Only repair selectors for IDs listed in FAILED_ELEMENTS.
2) Never change IDs.
3) For elements whose id exists in DOM id list, selector must be exactly '#<id>'.
4) Selector must target ONE intended user-relevant element whenever possible.
5) Do not invent new elements or triggers.

Schema:
{
    "elements": [
        {"id": "...", "selector": "..."}
    ]
}
"""


@dataclass
class Chunk:
    index: int
    start_line: int
    end_line: int
    char_count: int
    text: str

def _sanitize_backslashes(s: str) -> str:
    """Replace invalid JSON backslash escapes by scanning char by char."""
    valid_escapes = set('"\\\/bfnrtu')
    result = []
    i = 0
    while i < len(s):
        ch = s[i]
        if ch == '\\':
            nxt = s[i+1] if i+1 < len(s) else ''
            if nxt == 'u':
                # Check if followed by exactly 4 hex digits
                hex_part = s[i+2:i+6]
                if len(hex_part) == 4 and all(c in '0123456789abcdefABCDEF' for c in hex_part):
                    result.append('\\u')
                    i += 2
                    continue
                else:
                    result.append('\\\\u')
                    i += 2
                    continue
            elif nxt in valid_escapes:
                result.append('\\')
                result.append(nxt)
                i += 2
                continue
            else:
                result.append('\\\\')
                i += 1
                continue
        result.append(ch)
        i += 1
    return ''.join(result)

def extract_json_from_text(text: str) -> dict[str, Any]:
    text = text.strip()

    # Strip thinking blocks and markdown fences
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"```\s*$", "", text, flags=re.MULTILINE).strip()

    # Sanitize ALL invalid JSON backslash escapes BEFORE any parsing attempt.
    # Valid JSON escapes: \" \\ \/ \b \f \n \r \t \uXXXX
    # Strategy: replace any \ not followed by a valid escape char with \\
    # Do \uXXXX check first, then catch everything else.
    text = _sanitize_backslashes(text)

    # Try direct parse (works if output is clean JSON)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Find outermost JSON object
    start = text.find("{")
    if start == -1:
        raise ValueError("No JSON object found in LLM response")

    depth = 0
    end = -1
    in_string = False
    escape_next = False
    for i in range(start, len(text)):
        ch = text[i]
        if escape_next:
            escape_next = False
            continue
        if ch == "\\" and in_string:
            escape_next = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                break

    if end != -1:
        try:
            return json.loads(text[start:end])
        except json.JSONDecodeError as exc:
            # Print a wide window around the error position
            bad_pos = exc.pos
            print(f"[DEBUG] error at pos {bad_pos}: {repr(text[start:end][max(0,bad_pos-100):bad_pos+100])}")
            raise ValueError(f"JSON parse failed after sanitization: {exc}") from exc

    # Truncation recovery: LLM ran out of tokens mid-JSON
    partial = text[start:]
    stack = []
    in_string = False
    escape_next = False
    for ch in partial:
        if escape_next:
            escape_next = False
            continue
        if ch == "\\" and in_string:
            escape_next = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch in "{[":
            stack.append(ch)
        elif ch == "}" and stack and stack[-1] == "{":
            stack.pop()
        elif ch == "]" and stack and stack[-1] == "[":
            stack.pop()

    closing = "".join("]" if o == "[" else "}" for o in reversed(stack))
    trimmed = partial.rstrip().rstrip(",").rstrip()
    recovered = trimmed + closing
    try:
        result = json.loads(recovered)
        print("[WARN] LLM output was truncated; recovered partial JSON")
        return result
    except json.JSONDecodeError as exc:
        raise ValueError("Unclosed JSON object in LLM response") from exc

def ollama_chat(
    ollama_url: str,
    model: str,
    system_prompt: str,
    user_prompt: str,
    timeout_seconds: int,
    temperature: float = 0.1,
    num_predict: int = 4096,
    use_json_mode: bool = True,
    stream: bool = False,
    think: bool = False,
    print_stream: bool = False,
    ollama_token: str = "",
) -> str:
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "stream": stream,
        "think": think,
        "options": {
            "temperature": temperature,
            "num_predict": num_predict,
            "repeat_penalty": 1.1,
        },
    }
    
    # Use JSON mode for models that support it (Ollama 0.4+)
    # This constrains output to valid JSON only, improving reliability
    if use_json_mode:
        payload["format"] = "json"

    headers = {"Content-Type": "application/json"}
    if ollama_token:
        headers["X-API-Token"] = ollama_token

    req = request.Request(
        f"{ollama_url.rstrip('/')}/api/chat",
        method="POST",
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
    )

    try:
        with request.urlopen(req, timeout=timeout_seconds) as resp:
            if not stream:
                data = json.loads(resp.read().decode("utf-8"))
                return data["message"]["content"]

            parts: list[str] = []
            for raw_line in resp:
                line = raw_line.decode("utf-8", errors="ignore").strip()
                if not line:
                    continue

                chunk = json.loads(line)
                if chunk.get("error"):
                    raise RuntimeError(f"Ollama stream error: {chunk['error']}")

                text = (chunk.get("message") or {}).get("content", "")
                if text:
                    parts.append(text)
                    if print_stream:
                        print(text, end="", flush=True)

            if print_stream:
                print()
            return "".join(parts)
    except error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="ignore")
        raise RuntimeError(f"HTTP {exc.code} from Ollama: {body[:1000]}") from exc
    except error.URLError as exc:
        raise RuntimeError(f"Failed to connect to Ollama at {ollama_url}: {exc}") from exc


def remote_extract_chunk(
    *,
    server_url: str,
    api_token: str,
    filename: str,
    html_content: str,
    page_url: str,
    page_title: str,
    preferred_model: str,
    timeout_seconds: int,
    use_fallback: bool,
    stream: bool = False,
    show_stream: bool = False,
    show_thinking: bool = False,
) -> dict[str, Any]:
    payload = {
        "filename": filename,
        "skeleton": {
            "page_url": page_url,
            "page_title": page_title,
            "filename": filename,
            "html_content": html_content,
        },
        "preferred_model": preferred_model,
        "use_fallback": use_fallback,
    }

    if stream:
        payload["show_thinking"] = show_thinking

        stream_req = request.Request(
            f"{server_url.rstrip('/')}/extract/stream",
            method="POST",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "x-api-token": api_token,
            },
        )

        try:
            with request.urlopen(stream_req, timeout=timeout_seconds) as resp:
                streamed_chars = 0
                last_report = 0
                saw_final = False

                for raw_line in resp:
                    line = raw_line.decode("utf-8", errors="ignore").strip()
                    if not line:
                        continue

                    event = json.loads(line)
                    event_type = event.get("event")

                    if event_type == "model":
                        attempt = event.get("attempt")
                        total_attempts = event.get("total_attempts")
                        model_name = event.get("model", "")
                        print(f"    remote model attempt {attempt}/{total_attempts}: {model_name}")
                        continue

                    if event_type == "status":
                        print(f"    {event.get('message', '')}")
                        continue

                    if event_type == "token":
                        text = event.get("text", "")
                        if not text:
                            continue
                        if show_stream:
                            print(text, end="", flush=True)
                        else:
                            streamed_chars += len(text)
                            if streamed_chars - last_report >= 2000:
                                print(f"    streaming... {streamed_chars} chars")
                                last_report = streamed_chars
                        continue

                    if event_type == "final":
                        saw_final = True
                        if show_stream:
                            print()

                        if event.get("success"):
                            data = event.get("data")
                            if not isinstance(data, dict):
                                raise RuntimeError("Remote stream returned invalid final data payload")
                            return data

                        error_msg = str(event.get("error", "unknown error"))
                        parse_related_markers = (
                            "No JSON object found",
                            "Unclosed JSON object",
                            "JSON",
                            "Expecting",
                        )
                        if any(marker in error_msg for marker in parse_related_markers):
                            print(f"    stream JSON parse issue ({error_msg}); falling back to non-stream mode")
                            return remote_extract_chunk(
                                server_url=server_url,
                                api_token=api_token,
                                filename=filename,
                                html_content=html_content,
                                page_url=page_url,
                                page_title=page_title,
                                preferred_model=preferred_model,
                                timeout_seconds=timeout_seconds,
                                use_fallback=use_fallback,
                                stream=False,
                                show_stream=False,
                                show_thinking=False,
                            )

                        raise RuntimeError(f"Remote stream extract failed: {error_msg}")

                if not saw_final:
                    raise RuntimeError("Remote stream ended without final event")

        except error.HTTPError as exc:
            if exc.code in {404, 405}:
                print("    remote server has no /extract/stream endpoint; falling back to non-stream mode")
                return remote_extract_chunk(
                    server_url=server_url,
                    api_token=api_token,
                    filename=filename,
                    html_content=html_content,
                    page_url=page_url,
                    page_title=page_title,
                    preferred_model=preferred_model,
                    timeout_seconds=timeout_seconds,
                    use_fallback=use_fallback,
                    stream=False,
                    show_stream=False,
                    show_thinking=False,
                )
            body = exc.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"HTTP {exc.code} from remote stream endpoint: {body[:1000]}") from exc
        except error.URLError as exc:
            raise RuntimeError(f"Failed to connect to remote server at {server_url}: {exc}") from exc

    req = request.Request(
        f"{server_url.rstrip('/')}/extract",
        method="POST",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "x-api-token": api_token,
        },
    )

    try:
        with request.urlopen(req, timeout=timeout_seconds) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="ignore")
        raise RuntimeError(f"HTTP {exc.code} from remote server: {body[:1000]}") from exc
    except error.URLError as exc:
        raise RuntimeError(f"Failed to connect to remote server at {server_url}: {exc}") from exc

    if not body.get("success"):
        raise RuntimeError(f"Remote extract failed: {body.get('error', 'unknown error')}")

    data = body.get("data")
    if not isinstance(data, dict):
        raise RuntimeError("Remote extract returned invalid 'data' payload")
    return data


def remote_patch_missing(
    *,
    server_url: str,
    api_token: str,
    filename: str,
    html_content: str,
    page_url: str,
    page_title: str,
    existing_nkg: dict[str, Any],
    missing_ids: list[str],
    preferred_model: str,
    timeout_seconds: int,
    use_fallback: bool,
) -> dict[str, Any]:
    payload = {
        "filename": filename,
        "skeleton": {
            "page_url": page_url,
            "page_title": page_title,
            "filename": filename,
            "html_content": html_content,
        },
        "existing_nkg": existing_nkg,
        "missing_ids": missing_ids,
        "preferred_model": preferred_model,
        "use_fallback": use_fallback,
    }

    req = request.Request(
        f"{server_url.rstrip('/')}/extract/patch-missing",
        method="POST",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "x-api-token": api_token,
        },
    )

    try:
        with request.urlopen(req, timeout=timeout_seconds) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="ignore")
        raise RuntimeError(f"HTTP {exc.code} from remote patch endpoint: {body[:1000]}") from exc
    except error.URLError as exc:
        raise RuntimeError(f"Failed to connect to remote server at {server_url}: {exc}") from exc

    if not body.get("success"):
        raise RuntimeError(f"Remote patch failed: {body.get('error', 'unknown error')}")

    data = body.get("data")
    if not isinstance(data, dict):
        raise RuntimeError("Remote patch returned invalid 'data' payload")
    return data


def remote_reconcile_patch(
    *,
    server_url: str,
    api_token: str,
    filename: str,
    html_content: str,
    page_url: str,
    page_title: str,
    existing_nkg: dict[str, Any],
    preferred_model: str,
    timeout_seconds: int,
    use_fallback: bool,
) -> dict[str, Any]:
    payload = {
        "filename": filename,
        "skeleton": {
            "page_url": page_url,
            "page_title": page_title,
            "filename": filename,
            "html_content": html_content,
        },
        "existing_nkg": existing_nkg,
        "preferred_model": preferred_model,
        "use_fallback": use_fallback,
    }

    req = request.Request(
        f"{server_url.rstrip('/')}/extract/reconcile-patch",
        method="POST",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "x-api-token": api_token,
        },
    )

    try:
        with request.urlopen(req, timeout=timeout_seconds) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="ignore")
        raise RuntimeError(f"HTTP {exc.code} from remote reconcile endpoint: {body[:1000]}") from exc
    except error.URLError as exc:
        raise RuntimeError(f"Failed to connect to remote server at {server_url}: {exc}") from exc

    if not body.get("success"):
        raise RuntimeError(f"Remote reconcile failed: {body.get('error', 'unknown error')}")

    data = body.get("data")
    if not isinstance(data, dict):
        raise RuntimeError("Remote reconcile returned invalid 'data' payload")
    return data


def remote_repair_selectors(
    *,
    server_url: str,
    api_token: str,
    filename: str,
    html_content: str,
    page_url: str,
    page_title: str,
    elements_to_fix: list[dict[str, Any]],
    preferred_model: str,
    timeout_seconds: int,
    use_fallback: bool,
) -> dict[str, Any]:
    payload = {
        "filename": filename,
        "skeleton": {
            "page_url": page_url,
            "page_title": page_title,
            "filename": filename,
            "html_content": html_content,
        },
        "elements_to_fix": elements_to_fix,
        "preferred_model": preferred_model,
        "use_fallback": use_fallback,
    }

    req = request.Request(
        f"{server_url.rstrip('/')}/extract/repair-selectors",
        method="POST",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "x-api-token": api_token,
        },
    )

    try:
        with request.urlopen(req, timeout=timeout_seconds) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="ignore")
        raise RuntimeError(f"HTTP {exc.code} from remote selector repair endpoint: {body[:1000]}") from exc
    except error.URLError as exc:
        raise RuntimeError(f"Failed to connect to remote server at {server_url}: {exc}") from exc

    if not body.get("success"):
        raise RuntimeError(f"Remote selector repair failed: {body.get('error', 'unknown error')}")

    data = body.get("data")
    if not isinstance(data, dict):
        raise RuntimeError("Remote selector repair returned invalid 'data' payload")
    return data


def infer_page_url_from_filename(filename: str) -> str:
    stem = Path(filename).stem
    parts = [p for p in stem.split("_") if p]
    return "/" + "/".join(parts) if parts else "/unknown"


def extract_inline_scripts(html: str) -> str:
    """Extract inline <script> content (no src attr) from HTML for trigger context."""
    scripts = re.findall(r"<script(?:\s[^>]*)?>(.+?)</script>", html, re.DOTALL | re.IGNORECASE)
    # Filter: only keep scripts that are NOT just empty or whitespace
    inline = [s.strip() for s in scripts if s.strip() and not re.match(r"^\s*$", s)]
    if not inline:
        return ""
    return "<script>\n" + "\n</script>\n<script>\n".join(inline) + "\n</script>"


def extract_page_metadata_from_html(html: str) -> tuple[str, str]:
    """Extract page_url + page_title from btn_favorite attributes when available."""
    tag_match = re.search(r"<[^>]*\bid\s*=\s*['\"]btn_favorite['\"][^>]*>", html, flags=re.IGNORECASE)
    if not tag_match:
        return "", ""

    tag = tag_match.group(0)

    def _attr(name: str) -> str:
        m = re.search(rf"\b{name}\s*=\s*(['\"])(.*?)\1", tag, flags=re.IGNORECASE | re.DOTALL)
        return m.group(2).strip() if m else ""

    raw_url = _attr("menu_url")
    page_title = _attr("menu_name")

    page_url = ""
    if raw_url:
        m = re.search(r"(/customer/[^\s\"'#?]+)", raw_url)
        page_url = m.group(1) if m else raw_url

    return page_url, page_title


def infer_page_slug(page_url: str, fallback_filename: str) -> str:
    slug = page_url.rstrip("/").split("/")[-1]
    if slug:
        return slug
    return Path(fallback_filename).stem


def extract_title(html: str) -> str:
    m = re.search(r"<title[^>]*>(.*?)</title>", html, flags=re.IGNORECASE | re.DOTALL)
    if not m:
        return "Untitled"
    title = re.sub(r"\s+", " ", m.group(1)).strip()
    return title or "Untitled"


def parse_dom_ids_with_lines(html: str) -> dict[str, int]:
    id_line: dict[str, int] = {}
    pattern = re.compile(r"\bid\s*=\s*([\"'])([^\"']+)\1", flags=re.IGNORECASE)
    for m in pattern.finditer(html):
        dom_id = m.group(2).strip()
        if not dom_id:
            continue
        if dom_id not in id_line:
            line_no = html.count("\n", 0, m.start()) + 1
            id_line[dom_id] = line_no
    return id_line


def parse_dom_ids(html: str) -> set[str]:
    return set(parse_dom_ids_with_lines(html).keys())


def chunk_html(
    html: str,
    max_chars: int = 18000,
    overlap_chars: int = 1200,
) -> list[Chunk]:
    """
    Split HTML into roughly equal-sized chunks that:

    1. Never exceed `max_chars` (hard ceiling).
    2. Always snap cuts to a clean tag boundary so the LLM never receives
       a truncated opening/closing tag mid-token.
    3. Merge trailing micro-chunks (< 15 % of max_chars and 0 DOM ids) into
       the previous chunk so we never waste an LLM call on whitespace/noise.
    4. Add a context overlap at the start of every non-first chunk so the LLM
       has structural context without duplicating work.
    5. Aim for even chunk sizes by targeting `max_chars * 0.85` as the
       *preferred* cut point, then snapping forward to the next boundary — this
       avoids the old behaviour where boundary-snapping could produce one 2 kchar
       chunk followed by one 17 kchar chunk.
    """
    lines = html.splitlines(keepends=True)
    if not lines:
        return [Chunk(index=1, start_line=1, end_line=1, char_count=0, text="")]

    # Closing tags are preferred cut points because they represent completed
    # structural units.  Opening tags are fallback cuts.
    closing_boundary_re = re.compile(
        r"</(?:div|section|form|table|ul|nav|header|footer|main|article|aside|script)>",
        flags=re.IGNORECASE,
    )
    opening_boundary_re = re.compile(
        r"<(?:div|section|form|table|ul|nav|header|footer|main|article|aside|script)\b",
        flags=re.IGNORECASE,
    )
    id_attr_re = re.compile(r'\bid\s*=\s*["\'][^"\']+["\']', flags=re.IGNORECASE)

    # ------------------------------------------------------------------ #
    # Pre-compute cumulative char offsets so boundary search is O(1).     #
    # ------------------------------------------------------------------ #
    cum: list[int] = [0] * (len(lines) + 1)
    for i, ln in enumerate(lines):
        cum[i + 1] = cum[i] + len(ln)

    def chars_in_range(a: int, b: int) -> int:
        """Char count for lines[a:b] (0-indexed)."""
        return cum[b] - cum[a]

    def dom_ids_in_range(a: int, b: int) -> int:
        return sum(1 for ln in lines[a:b] if id_attr_re.search(ln))

    # ------------------------------------------------------------------ #
    # Find the best snap point starting at `search_from` (inclusive),     #
    # scanning forward up to `search_to` (exclusive).                     #
    # Returns the line index *after* the cut (i.e. lines[:cut] is kept).  #
    # Prefers closing tags; falls back to opening tags; falls back to      #
    # `search_to` itself if no boundary is found.                          #
    # ------------------------------------------------------------------ #
    def best_snap(search_from: int, search_to: int) -> int:
        best_close: int | None = None
        best_open: int | None = None
        for i in range(search_from, search_to):
            line = lines[i]
            if closing_boundary_re.search(line):
                best_close = i + 1   # cut *after* this line
            elif opening_boundary_re.search(line) and best_open is None:
                best_open = i        # cut *before* this opening tag
        if best_close is not None:
            return best_close
        if best_open is not None:
            return best_open
        return search_to

    # ------------------------------------------------------------------ #
    # Main chunking loop                                                   #
    # ------------------------------------------------------------------ #
    # We target `preferred_chars` as the soft size and use `max_chars` as
    # the hard ceiling.  Targeting 85 % of max keeps us well below the
    # ceiling after boundary snapping (which can only add lines, not remove
    # them) and produces chunks that are visually similar in size.
    preferred_chars = int(max_chars * 0.85)

    raw_chunks: list[tuple[int, int]] = []   # (start_line_0idx, end_line_0idx exclusive)
    start = 0

    while start < len(lines):
        total_remaining = chars_in_range(start, len(lines))

        # If whatever is left fits in one chunk, take it all.
        if total_remaining <= max_chars:
            raw_chunks.append((start, len(lines)))
            break

        # Walk forward to find where we hit the preferred target.
        preferred_end = start
        acc = 0
        while preferred_end < len(lines):
            acc += len(lines[preferred_end])
            preferred_end += 1
            if acc >= preferred_chars:
                break

        # Search for a snap point in the window [preferred_end, hard_limit].
        # This ensures we never go below preferred and never exceed hard.
        hard_end = start
        acc2 = 0
        while hard_end < len(lines):
            acc2 += len(lines[hard_end])
            hard_end += 1
            if acc2 >= max_chars:
                break

        snap = best_snap(preferred_end, hard_end)
        # Guard: snap must always advance past start by at least one line.
        snap = max(snap, start + 1)
        # Guard: never exceed hard ceiling.
        if chars_in_range(start, snap) > max_chars:
            snap = hard_end

        raw_chunks.append((start, snap))

        # Compute overlap: rewind from `snap` to include `overlap_chars` of
        # context.  This gives the next chunk structural awareness without
        # duplicating a full chunk's worth of content.
        back = snap
        overlap_acc = 0
        while back > start and overlap_acc < overlap_chars:
            back -= 1
            overlap_acc += len(lines[back])

        next_start = back if back > start else snap
        # Safety: always advance.
        if next_start <= start:
            next_start = snap
        start = next_start

    # ------------------------------------------------------------------ #
    # Post-process: merge micro tail-chunks into the previous chunk.      #
    # A chunk is a "micro tail" when it is the last chunk AND             #
    # its char count < 15 % of max_chars AND it contains 0 DOM ids.      #
    # ------------------------------------------------------------------ #
    micro_threshold = int(max_chars * 0.15)

    while len(raw_chunks) >= 2:
        last_s, last_e = raw_chunks[-1]
        tail_chars = chars_in_range(last_s, last_e)
        tail_ids = dom_ids_in_range(last_s, last_e)
        if tail_chars <= micro_threshold and tail_ids == 0:
            # Absorb into the previous chunk (ignoring overlap boundary).
            prev_s, _ = raw_chunks[-2]
            raw_chunks[-2] = (prev_s, last_e)
            raw_chunks.pop()
        else:
            break

    # ------------------------------------------------------------------ #
    # Build Chunk objects                                                  #
    # ------------------------------------------------------------------ #
    chunks: list[Chunk] = []
    for idx, (s, e) in enumerate(raw_chunks, start=1):
        text = "".join(lines[s:e])
        chunks.append(
            Chunk(
                index=idx,
                start_line=s + 1,
                end_line=e,
                char_count=chars_in_range(s, e),
                text=text,
            )
        )

    # Re-index after potential merges.
    for i, ch in enumerate(chunks, start=1):
        ch.index = i

    return chunks


def validate_nkg_fragment(data: dict[str, Any]) -> None:
    if "page" not in data or not isinstance(data["page"], dict):
        raise ValueError("Missing/invalid page")
    if "elements" not in data or not isinstance(data["elements"], list):
        raise ValueError("Missing/invalid elements list")
    if "triggers" not in data or not isinstance(data["triggers"], list):
        raise ValueError("Missing/invalid triggers list")


def normalize_element(el: dict[str, Any], dom_ids: set[str], page_slug: str) -> dict[str, Any]:
    element_id = str(el.get("id", "")).strip()
    desc = str(el.get("desc", "")).strip()
    element_type = str(el.get("type", "section")).strip() or "section"
    selector = str(el.get("selector", "")).strip()
    parent_element_id = str(el.get("parent_element_id", "")).strip()

    if not element_id:
        return {}

    if element_id in dom_ids:
        selector = f"#{element_id}"
    elif not selector:
        selector = f"[data-nkg-id='{element_id}']"

    if "__" not in element_id and element_id not in dom_ids:
        element_id = f"{page_slug}__{element_id}"

    if parent_element_id:
        if "__" not in parent_element_id and parent_element_id not in dom_ids:
            parent_element_id = f"{page_slug}__{parent_element_id}"
        if parent_element_id == element_id:
            parent_element_id = ""

    if not desc:
        desc = "Elemen antarmuka untuk interaksi pengguna"

    normalized = {
        "id": element_id,
        "desc": desc,
        "type": element_type,
        "selector": selector,
    }

    if parent_element_id:
        normalized["parent_element_id"] = parent_element_id

    return normalized


def normalize_trigger(tr: dict[str, Any]) -> dict[str, Any]:
    from_id = str(tr.get("from", "")).strip()
    to = str(tr.get("to", "")).strip()
    to_type = str(tr.get("to_type", "")).strip()

    if not from_id or not to:
        return {}

    if to_type not in {"element", "page"}:
        to_type = "page" if to.startswith("/") else "element"

    return {"from": from_id, "to": to, "to_type": to_type}


def merge_nkg(base: dict[str, Any], fragment: dict[str, Any], dom_ids: set[str], page_slug: str) -> dict[str, Any]:
    page = base.get("page") or fragment.get("page") or {}

    existing_elements: dict[str, dict[str, Any]] = {
        e["id"]: e for e in base.get("elements", []) if isinstance(e, dict) and "id" in e
    }

    for raw_el in fragment.get("elements", []):
        if not isinstance(raw_el, dict):
            continue
        el = normalize_element(raw_el, dom_ids, page_slug)
        if not el:
            continue

        if el["id"] not in existing_elements:
            existing_elements[el["id"]] = el
        else:
            old = existing_elements[el["id"]]
            if len(el.get("desc", "")) > len(old.get("desc", "")):
                old["desc"] = el["desc"]
            if old.get("type") in {"", "section"} and el.get("type"):
                old["type"] = el["type"]
            if el["id"] in dom_ids:
                old["selector"] = f"#{el['id']}"
            elif not old.get("selector") and el.get("selector"):
                old["selector"] = el["selector"]
            if not old.get("parent_element_id") and el.get("parent_element_id"):
                old["parent_element_id"] = el["parent_element_id"]

    final_ids = set(existing_elements.keys())
    for element_id, element in existing_elements.items():
        parent_id = str(element.get("parent_element_id", "")).strip()
        if not parent_id:
            element.pop("parent_element_id", None)
            continue
        if parent_id == element_id or parent_id not in final_ids:
            element.pop("parent_element_id", None)

    trig_set = {
        (t.get("from"), t.get("to"), t.get("to_type"))
        for t in base.get("triggers", [])
        if isinstance(t, dict)
    }
    triggers = [t for t in base.get("triggers", []) if isinstance(t, dict)]

    for raw_tr in fragment.get("triggers", []):
        if not isinstance(raw_tr, dict):
            continue
        tr = normalize_trigger(raw_tr)
        if not tr:
            continue
        key = (tr["from"], tr["to"], tr["to_type"])
        if key not in trig_set:
            trig_set.add(key)
            triggers.append(tr)

    merged = {
        "page": {
            "id": str(page.get("id", "")).strip() or base.get("page", {}).get("id", ""),
            "title": str(page.get("title", "")).strip() or base.get("page", {}).get("title", "Untitled"),
            "desc": str(page.get("desc", "")).strip() or base.get("page", {}).get("desc", "Halaman admin untuk pengelolaan data."),
        },
        "elements": sorted(existing_elements.values(), key=lambda x: x["id"]),
        "triggers": triggers,
    }
    return merged


def build_chunk_prompt(
    *,
    page_url: str,
    page_title: str,
    page_slug: str,
    chunk: Chunk,
    total_chunks: int,
    chunk_dom_ids: list[str],
    known_ids: list[str],
    one_shot_example: dict[str, Any] | None,
    script_context: str = "",
) -> str:
    one_shot_block = ""
    if one_shot_example:
        one_shot_min = {
            "page": one_shot_example.get("page", {}),
            "elements": one_shot_example.get("elements", [])[:60],
            "triggers": one_shot_example.get("triggers", [])[:100],
        }
        one_shot_block = (
            "ONE-SHOT EXAMPLE (ikuti gaya dan kualitas ini, tapi JANGAN copy id/route dari contoh):\n"
            + json.dumps(one_shot_min, ensure_ascii=False)
            + "\n\n"
        )

    return (
        f"{one_shot_block}"
        "Task: Extract NKG from this HTML chunk.\n\n"
        f"PAGE_URL: {page_url}\n"
        f"PAGE_TITLE: {page_title}\n"
        f"PAGE_SLUG: {page_slug}\n"
        f"CHUNK_INDEX: {chunk.index}/{total_chunks}\n"
        f"CHUNK_LINES: {chunk.start_line}-{chunk.end_line}\n"
        f"DOM_IDS_IN_THIS_CHUNK: {json.dumps(chunk_dom_ids, ensure_ascii=False)}\n"
        f"KNOWN_ELEMENT_IDS_FROM_PREVIOUS_CHUNKS: {json.dumps(known_ids, ensure_ascii=False)}\n\n"
        "IMPORTANT: untuk id yang ada di DOM_IDS_IN_THIS_CHUNK, usahakan semua ter-cover sebagai elements jika memang muncul di chunk ini.\n"
        "IMPORTANT: jangan duplikasi id yang sudah ada di KNOWN_ELEMENT_IDS_FROM_PREVIOUS_CHUNKS.\n\n"
        "HTML_CHUNK:\n"
        f"{chunk.text}\n"
        + (f"\nSCRIPT_CONTEXT (fungsi JS yang dipanggil onclick di atas, gunakan untuk identifikasi trigger):\n{script_context}\n" if script_context else "")
    )


def build_patch_prompt(
    *,
    page_url: str,
    page_title: str,
    chunk: Chunk,
    missing_ids: list[str],
    existing_nkg: dict[str, Any],
) -> str:
    current_ids = [e.get("id") for e in existing_nkg.get("elements", []) if isinstance(e, dict) and e.get("id")]
    compact_existing = {
        "page": existing_nkg.get("page", {}),
        "elements": [
            {
                "id": e.get("id"),
                "type": e.get("type"),
                "selector": e.get("selector"),
                "parent_element_id": e.get("parent_element_id"),
            }
            for e in existing_nkg.get("elements", [])
            if isinstance(e, dict)
        ],
        "triggers": existing_nkg.get("triggers", []),
    }

    return (
        "Insertion-only patch for missing DOM ids in this chunk.\n\n"
        f"PAGE_URL: {page_url}\n"
        f"PAGE_TITLE: {page_title}\n"
        f"CHUNK_INDEX: {chunk.index}\n"
        f"CHUNK_LINES: {chunk.start_line}-{chunk.end_line}\n"
        f"MISSING_DOM_IDS: {json.dumps(missing_ids, ensure_ascii=False)}\n"
        f"EXISTING_ELEMENT_IDS: {json.dumps(current_ids, ensure_ascii=False)}\n\n"
        "TASK:\n"
        "- Put user-relevant ids into elements[].\n"
        "- Put noise/non-actionable ids into excluded[] with short reason.\n"
        "- Do not force all ids into elements[].\n\n"
        "EXISTING_NKG_COMPACT:\n"
        f"{json.dumps(compact_existing, ensure_ascii=False)}\n\n"
        "HTML_CHUNK:\n"
        f"{chunk.text}\n"
    )


def build_global_reconcile_prompt(
    *,
    page_url: str,
    page_title: str,
    page_slug: str,
    existing_nkg: dict[str, Any],
    html: str,
) -> str:
    compact_existing = {
        "page": existing_nkg.get("page", {}),
        "elements": [
            {
                "id": e.get("id"),
                "type": e.get("type"),
                "selector": e.get("selector"),
                "parent_element_id": e.get("parent_element_id"),
            }
            for e in existing_nkg.get("elements", [])
            if isinstance(e, dict)
        ],
        "triggers": existing_nkg.get("triggers", []),
    }

    return (
        "Patch-only global reconciliation for chunk-boundary misses.\n\n"
        f"PAGE_URL: {page_url}\n"
        f"PAGE_TITLE: {page_title}\n"
        f"PAGE_SLUG: {page_slug}\n\n"
        "EXISTING_NKG_COMPACT:\n"
        f"{json.dumps(compact_existing, ensure_ascii=False)}\n\n"
        "TASK:\n"
        "- Add/repair only needed elements/triggers; do not regenerate full output.\n"
        "- Keep valid existing ids/selectors; add only useful missing items.\n"
        "- Return PATCH schema exactly: elements[] and triggers[] only.\n\n"
        "FULL_HTML:\n"
        f"{html}\n"
    )


def build_selector_repair_prompt(
    *,
    page_url: str,
    page_title: str,
    page_slug: str,
    failed_elements: list[dict[str, Any]],
    existing_nkg: dict[str, Any],
    html: str,
) -> str:
    compact_existing = {
        "page": existing_nkg.get("page", {}),
        "elements": [
            {
                "id": e.get("id"),
                "selector": e.get("selector"),
                "type": e.get("type"),
            }
            for e in existing_nkg.get("elements", [])
            if isinstance(e, dict)
        ],
    }

    return (
        "Repair selectors for failed NKG elements only.\n\n"
        f"PAGE_URL: {page_url}\n"
        f"PAGE_TITLE: {page_title}\n"
        f"PAGE_SLUG: {page_slug}\n"
        f"FAILED_ELEMENTS: {json.dumps(failed_elements, ensure_ascii=False)}\n\n"
        "EXISTING_NKG_COMPACT:\n"
        f"{json.dumps(compact_existing, ensure_ascii=False)}\n\n"
        "FULL_HTML:\n"
        f"{html}\n"
    )


def validate_selector_targets(nkg: dict[str, Any], html: str, dom_ids: set[str]) -> dict[str, Any]:
    if BeautifulSoup is None:
        return {
            "available": False,
            "summary": {"message": "bs4 not installed; selector validation skipped"},
            "failed": [],
        }

    soup = BeautifulSoup(html, "html.parser")
    failed: list[dict[str, Any]] = []
    valid_single = 0
    ambiguous_multi = 0
    not_found = 0
    invalid_selector = 0
    missing_selector = 0

    for el in nkg.get("elements", []):
        if not isinstance(el, dict):
            continue

        element_id = str(el.get("id", "")).strip()
        selector = str(el.get("selector", "")).strip()
        if not element_id:
            continue

        if not selector:
            missing_selector += 1
            failed.append({
                "id": element_id,
                "selector": selector,
                "status": "missing_selector",
                "type": el.get("type", ""),
                "desc": el.get("desc", ""),
            })
            continue

        try:
            matches = soup.select(selector)
        except Exception as exc:  # noqa: BLE001
            invalid_selector += 1
            failed.append({
                "id": element_id,
                "selector": selector,
                "status": "invalid_selector",
                "error": str(exc),
                "type": el.get("type", ""),
                "desc": el.get("desc", ""),
            })
            continue

        match_count = len(matches)
        if match_count == 1:
            valid_single += 1
            continue

        status = "not_found" if match_count == 0 else "ambiguous_multi"
        if status == "not_found":
            not_found += 1
        else:
            ambiguous_multi += 1

        failed.append({
            "id": element_id,
            "selector": selector,
            "status": status,
            "match_count": match_count,
            "is_dom_id_element": element_id in dom_ids,
            "type": el.get("type", ""),
            "desc": el.get("desc", ""),
        })

    total = valid_single + ambiguous_multi + not_found + invalid_selector + missing_selector
    return {
        "available": True,
        "summary": {
            "total_checked": total,
            "valid_single": valid_single,
            "ambiguous_multi": ambiguous_multi,
            "not_found": not_found,
            "invalid_selector": invalid_selector,
            "missing_selector": missing_selector,
            "failed_total": len(failed),
        },
        "failed": failed,
    }


def compute_verification(nkg: dict[str, Any], dom_ids: set[str], dom_id_lines: dict[str, int]) -> dict[str, Any]:
    element_ids = {e.get("id") for e in nkg.get("elements", []) if isinstance(e, dict) and e.get("id")}
    dom_ids_in_nkg = sorted(x for x in element_ids if x in dom_ids)
    missing_dom_ids = sorted(x for x in dom_ids if x not in element_ids)
    generated_ids = sorted(x for x in element_ids if x not in dom_ids)

    selector_mismatches = []
    for e in nkg.get("elements", []):
        if not isinstance(e, dict):
            continue
        element_id = e.get("id")
        if element_id in dom_ids and e.get("selector") != f"#{element_id}":
            selector_mismatches.append(
                {
                    "id": element_id,
                    "expected": f"#{element_id}",
                    "actual": e.get("selector"),
                }
            )

    missing_with_lines = [{"id": x, "line": dom_id_lines.get(x)} for x in missing_dom_ids]

    return {
        "dom_ids_total": len(dom_ids),
        "dom_ids_in_nkg_total": len(dom_ids_in_nkg),
        "coverage_percent": round((len(dom_ids_in_nkg) / len(dom_ids) * 100), 2) if dom_ids else 100.0,
        "missing_dom_ids": missing_dom_ids,
        "missing_dom_ids_with_line": missing_with_lines,
        "generated_non_dom_ids": generated_ids,
        "selector_mismatches": selector_mismatches,
        "is_complete": len(missing_dom_ids) == 0,
    }


def build_cypher_payload(nkg: dict[str, Any]) -> dict[str, Any]:
    page = nkg.get("page", {})
    elements = nkg.get("elements", [])
    triggers = nkg.get("triggers", [])

    valid_element_ids = {
        e.get("id")
        for e in elements
        if isinstance(e, dict) and e.get("id")
    }

    contains = [
        {"page_id": page.get("id"), "element_id": e.get("id")}
        for e in elements
        if isinstance(e, dict) and e.get("id") and not e.get("parent_element_id")
    ]

    element_contains = [
        {"parent_id": e.get("parent_element_id"), "child_id": e.get("id")}
        for e in elements
        if isinstance(e, dict)
        and e.get("id")
        and e.get("parent_element_id")
        and e.get("parent_element_id") in valid_element_ids
        and e.get("parent_element_id") != e.get("id")
    ]

    cypher_template = {
        "upsert_nodes_and_edges": (
            "MERGE (p:Page {id: $page.id}) "
            "SET p.title = $page.title, p.desc = $page.desc "
            "WITH p "
            "UNWIND $elements AS e "
            "MERGE (el:Element {id: e.id}) "
            "SET el.desc = e.desc, el.type = e.type, el.selector = e.selector "
            "WITH p "
            "UNWIND $contains AS c "
            "MATCH (el:Element {id: c.element_id}) "
            "MERGE (p)-[:CONTAINS]->(el);"
        ),
        "upsert_element_contains": (
            "UNWIND $element_contains AS c "
            "MATCH (parent:Element {id: c.parent_id}) "
            "MATCH (child:Element {id: c.child_id}) "
            "MERGE (parent)-[:CONTAINS]->(child);"
        ),
        "upsert_triggers": (
            "UNWIND $triggers AS t "
            "MATCH (from:Element {id: t.from}) "
            "FOREACH (_ IN CASE WHEN t.to_type = 'element' THEN [1] ELSE [] END | "
            "  MERGE (toEl:Element {id: t.to}) "
            "  MERGE (from)-[:TRIGGERS]->(toEl) "
            ") "
            "FOREACH (_ IN CASE WHEN t.to_type = 'page' THEN [1] ELSE [] END | "
            "  MERGE (toPg:Page {id: t.to}) "
            "  MERGE (from)-[:TRIGGERS]->(toPg) "
            ");"
        ),
    }

    return {
        "params": {
            "page": page,
            "elements": elements,
            "contains": contains,
            "element_contains": element_contains,
            "triggers": triggers,
        },
        "cypher_templates": cypher_template,
    }


def run(args: argparse.Namespace) -> dict[str, Any]:
    html_path = Path(args.html)
    if not html_path.exists():
        raise FileNotFoundError(f"HTML file not found: {html_path}")

    html = html_path.read_text(encoding="utf-8", errors="ignore")
    filename = html_path.name

    # Extract inline script context for trigger identification (optional)
    script_context = ""
    if getattr(args, "script_context", ""):
        script_path = Path(args.script_context)
        if script_path.exists():
            script_context = extract_inline_scripts(script_path.read_text(encoding="utf-8", errors="ignore"))
        elif args.script_context == "auto":
            script_context = extract_inline_scripts(html)
    elif getattr(args, "script_html", ""):
        script_html_path = Path(args.script_html)
        if script_html_path.exists():
            script_context = extract_inline_scripts(script_html_path.read_text(encoding="utf-8", errors="ignore"))

    detected_page_url, detected_page_title = extract_page_metadata_from_html(html)

    page_url = args.page_url or detected_page_url or infer_page_url_from_filename(filename)
    page_title = args.page_title or detected_page_title or extract_title(html)
    page_slug = infer_page_slug(page_url, filename)

    dom_id_lines = parse_dom_ids_with_lines(html)
    dom_ids = set(dom_id_lines.keys())

    chunks = chunk_html(html, max_chars=args.chunk_chars, overlap_chars=args.overlap_chars)
    backend = args.backend

    one_shot_example = None
    if args.one_shot_example:
        example_obj = json.loads(Path(args.one_shot_example).read_text(encoding="utf-8"))
        if "nkg" in example_obj:
            one_shot_example = example_obj["nkg"]
        else:
            one_shot_example = example_obj

    merged_nkg: dict[str, Any] = {
        "page": {
            "id": page_url,
            "title": page_title,
            "desc": "Halaman admin untuk mendukung alur kerja pengguna.",
        },
        "elements": [],
        "triggers": [],
    }

    chunk_reports: list[dict[str, Any]] = []
    started = time.time()

    if args.parallel_chunks and args.dry_run:
        print("[PARALLEL] dry-run mode detected; falling back to sequential prompt capture")
    if args.parallel_chunks and args.stream:
        print("[PARALLEL] stream is disabled in parallel mode to avoid interleaved output")
        args.stream = False
    if args.parallel_chunks and args.show_thinking:
        print("[PARALLEL] show-thinking is disabled in parallel mode")
        args.show_thinking = False
    
    # DRY-RUN MODE: collect prompts without calling LLM
    if args.dry_run:
        dry_run_prompts: list[dict[str, Any]] = []

    def apply_chunk_output(chunk: Chunk, chunk_dom_ids: list[str], data: dict[str, Any]) -> None:
        nonlocal merged_nkg

        before_ids = {e.get("id") for e in merged_nkg["elements"] if isinstance(e, dict)}
        merged_nkg = merge_nkg(merged_nkg, data, dom_ids, page_slug)
        after_ids = {e.get("id") for e in merged_nkg["elements"] if isinstance(e, dict)}

        missing_after_chunk = sorted(x for x in chunk_dom_ids if x not in after_ids)

        patched_added = 0
        patch_excluded = 0
        patch_error = None
        if args.patch_missing and missing_after_chunk:
            patch_prompt = build_patch_prompt(
                page_url=page_url,
                page_title=page_title,
                chunk=chunk,
                missing_ids=missing_after_chunk,
                existing_nkg=merged_nkg,
            )
            try:
                pre_patch_ids = {e.get("id") for e in merged_nkg["elements"] if isinstance(e, dict)}
                if backend == "remote":
                    merged_nkg = remote_patch_missing(
                        server_url=args.remote_server_url,
                        api_token=args.remote_api_token,
                        filename=filename,
                        html_content=chunk.text,
                        page_url=page_url,
                        page_title=page_title,
                        existing_nkg=merged_nkg,
                        missing_ids=missing_after_chunk,
                        preferred_model=args.model,
                        timeout_seconds=args.timeout,
                        use_fallback=args.remote_use_fallback,
                    )
                else:
                    patch_raw = ollama_chat(
                        ollama_url=args.ollama_url,
                        model=args.model,
                        system_prompt=PATCH_SYSTEM_PROMPT,
                        user_prompt=patch_prompt,
                        timeout_seconds=args.timeout,
                        temperature=args.temperature,
                        num_predict=args.num_predict,
                        use_json_mode=True,
                        ollama_token=args.ollama_token,
                    )
                    patch_data = extract_json_from_text(patch_raw)
                    if not isinstance(patch_data.get("elements", []), list):
                        raise ValueError("Patch response field 'elements' must be a list")
                    if not isinstance(patch_data.get("triggers", []), list):
                        raise ValueError("Patch response field 'triggers' must be a list")
                    if "excluded" in patch_data and not isinstance(patch_data.get("excluded"), list):
                        raise ValueError("Patch response field 'excluded' must be a list when provided")

                    patch_fragment = {
                        "page": merged_nkg["page"],
                        "elements": patch_data.get("elements", []),
                        "triggers": patch_data.get("triggers", []),
                    }
                    merged_nkg = merge_nkg(merged_nkg, patch_fragment, dom_ids, page_slug)
                    patch_excluded = len(patch_data.get("excluded", []))
                post_patch_ids = {e.get("id") for e in merged_nkg["elements"] if isinstance(e, dict)}
                patched_added = len(post_patch_ids - pre_patch_ids)
            except Exception as exc:  # noqa: BLE001
                patch_error = str(exc)

        chunk_reports.append(
            {
                "chunk_index": chunk.index,
                "line_range": [chunk.start_line, chunk.end_line],
                "char_count": chunk.char_count,
                "dom_ids_in_chunk": len(chunk_dom_ids),
                "new_ids_added": len(after_ids - before_ids),
                "missing_dom_ids_after_chunk": missing_after_chunk,
                "patch_added": patched_added,
                "patch_excluded": patch_excluded,
                "patch_error": patch_error,
            }
        )

    if args.parallel_chunks and not args.dry_run:
        print(f"[PARALLEL] chunk inference enabled | workers={max(1, args.parallel_workers)}")
        chunk_meta: dict[int, dict[str, Any]] = {}
        for chunk in chunks:
            chunk_dom_ids = sorted(parse_dom_ids(chunk.text))
            chunk_meta[chunk.index] = {
                "chunk": chunk,
                "chunk_dom_ids": chunk_dom_ids,
            }
            print(
                f"[{chunk.index}/{len(chunks)}] lines {chunk.start_line}-{chunk.end_line} | "
                f"{chunk.char_count} chars | dom_ids={len(chunk_dom_ids)}"
            )

        def infer_chunk(chunk: Chunk, chunk_dom_ids: list[str]) -> tuple[int, dict[str, Any], float]:
            user_prompt = build_chunk_prompt(
                page_url=page_url,
                page_title=page_title,
                page_slug=page_slug,
                chunk=chunk,
                total_chunks=len(chunks),
                chunk_dom_ids=chunk_dom_ids,
                known_ids=[],
                one_shot_example=one_shot_example,
                script_context=script_context,
            )

            t_chunk = time.time()
            if backend == "remote":
                data = remote_extract_chunk(
                    server_url=args.remote_server_url,
                    api_token=args.remote_api_token,
                    filename=filename,
                    html_content=chunk.text,
                    page_url=page_url,
                    page_title=page_title,
                    preferred_model=args.model,
                    timeout_seconds=args.timeout,
                    use_fallback=args.remote_use_fallback,
                    stream=False,
                    show_stream=False,
                    show_thinking=False,
                )
            else:
                raw = ollama_chat(
                    ollama_url=args.ollama_url,
                    model=args.model,
                    system_prompt=CHUNK_SYSTEM_PROMPT,
                    user_prompt=user_prompt,
                    timeout_seconds=args.timeout,
                    temperature=args.temperature,
                    num_predict=args.num_predict,
                    use_json_mode=True,
                    stream=False,
                    think=False,
                    print_stream=False,
                    ollama_token=args.ollama_token,
                )
                data = extract_json_from_text(raw)

            validate_nkg_fragment(data)
            return chunk.index, data, time.time() - t_chunk

        chunk_data_map: dict[int, dict[str, Any]] = {}
        with ThreadPoolExecutor(max_workers=max(1, args.parallel_workers)) as executor:
            future_map = {
                executor.submit(infer_chunk, meta["chunk"], meta["chunk_dom_ids"]): idx
                for idx, meta in chunk_meta.items()
            }
            for future in as_completed(future_map):
                chunk_index, data, elapsed = future.result()
                chunk_data_map[chunk_index] = data
                print(f"  done: chunk {chunk_index}/{len(chunks)} in {elapsed:.1f}s")

        for index in range(1, len(chunks) + 1):
            meta = chunk_meta[index]
            apply_chunk_output(meta["chunk"], meta["chunk_dom_ids"], chunk_data_map[index])

    else:
        for chunk in chunks:
            chunk_dom_ids = sorted(parse_dom_ids(chunk.text))
            known_ids = sorted({e.get("id") for e in merged_nkg["elements"] if isinstance(e, dict) and e.get("id")})

            print(
                f"[{chunk.index}/{len(chunks)}] lines {chunk.start_line}-{chunk.end_line} | "
                f"{chunk.char_count} chars | dom_ids={len(chunk_dom_ids)}"
            )

            user_prompt = build_chunk_prompt(
                page_url=page_url,
                page_title=page_title,
                page_slug=page_slug,
                chunk=chunk,
                total_chunks=len(chunks),
                chunk_dom_ids=chunk_dom_ids,
                known_ids=known_ids,
                one_shot_example=one_shot_example,
                script_context=script_context,
            )

            # DRY-RUN MODE: save prompt without calling LLM
            if args.dry_run:
                dry_run_prompts.append({
                    "chunk_index": chunk.index,
                    "line_range": [chunk.start_line, chunk.end_line],
                    "char_count": chunk.char_count,
                    "system_prompt": CHUNK_SYSTEM_PROMPT[:500],  # First 500 chars preview
                    "user_prompt": user_prompt,
                })
                print("  dry-run: prompt captured")
                continue

            t_chunk = time.time()
            if backend == "remote":
                print(f"  infer: remote {args.remote_server_url} | model={args.model} | stream={args.stream}")
                data = remote_extract_chunk(
                    server_url=args.remote_server_url,
                    api_token=args.remote_api_token,
                    filename=filename,
                    html_content=chunk.text,
                    page_url=page_url,
                    page_title=page_title,
                    preferred_model=args.model,
                    timeout_seconds=args.timeout,
                    use_fallback=args.remote_use_fallback,
                    stream=args.stream,
                    show_stream=args.stream and args.show_thinking,
                    show_thinking=args.show_thinking,
                )
                print(f"  done: remote in {time.time() - t_chunk:.1f}s")
            else:
                print(f"  infer: local {args.ollama_url} | model={args.model} | stream={args.stream}")
                raw = ollama_chat(
                    ollama_url=args.ollama_url,
                    model=args.model,
                    system_prompt=CHUNK_SYSTEM_PROMPT,
                    user_prompt=user_prompt,
                    timeout_seconds=args.timeout,
                    temperature=args.temperature,
                    num_predict=args.num_predict,
                    use_json_mode=True,
                    stream=args.stream,
                    think=args.show_thinking,
                    print_stream=args.stream and args.show_thinking,
                    ollama_token=args.ollama_token,
                )
                print(f"  done: local in {time.time() - t_chunk:.1f}s")
                data = extract_json_from_text(raw)
            validate_nkg_fragment(data)

            apply_chunk_output(chunk, chunk_dom_ids, data)

    if not args.dry_run and args.global_reconcile_pass:
        print("\n[GLOBAL] patch-only reconciliation pass over full HTML to catch cross-chunk relations")
        t_global = time.time()
        before_el = len(merged_nkg.get("elements", []))
        before_tr = len(merged_nkg.get("triggers", []))

        if backend == "remote":
            global_patch = remote_reconcile_patch(
                server_url=args.remote_server_url,
                api_token=args.remote_api_token,
                filename=filename,
                html_content=html,
                page_url=page_url,
                page_title=page_title,
                existing_nkg=merged_nkg,
                preferred_model=args.model,
                timeout_seconds=args.timeout,
                use_fallback=args.remote_use_fallback,
            )
        else:
            global_prompt = build_global_reconcile_prompt(
                page_url=page_url,
                page_title=page_title,
                page_slug=page_slug,
                existing_nkg=merged_nkg,
                html=html,
            )
            raw_global = ollama_chat(
                ollama_url=args.ollama_url,
                model=args.model,
                system_prompt=GLOBAL_RECONCILE_SYSTEM_PROMPT,
                user_prompt=global_prompt,
                timeout_seconds=args.timeout,
                temperature=args.temperature,
                num_predict=args.num_predict,
                use_json_mode=True,
                stream=args.stream,
                think=args.show_thinking,
                print_stream=args.stream and args.show_thinking,
                ollama_token=args.ollama_token,
            )
            global_patch = extract_json_from_text(raw_global)

        if not isinstance(global_patch.get("elements"), list) or not isinstance(global_patch.get("triggers"), list):
            raise ValueError("Global reconcile patch must include elements[] and triggers[]")

        patch_fragment = {
            "page": merged_nkg["page"],
            "elements": global_patch.get("elements", []),
            "triggers": global_patch.get("triggers", []),
        }
        merged_nkg = merge_nkg(merged_nkg, patch_fragment, dom_ids, page_slug)

        after_el = len(merged_nkg.get("elements", []))
        after_tr = len(merged_nkg.get("triggers", []))
        print(
            f"[GLOBAL] done in {time.time() - t_global:.1f}s | "
            f"+{after_el - before_el} elements | +{after_tr - before_tr} triggers"
        )

    selector_validation = {"available": False, "summary": {"message": "selector validation disabled"}, "failed": []}
    selector_repair: dict[str, Any] = {
        "attempted": False,
        "applied_updates": 0,
        "requested_ids": 0,
        "error": None,
    }

    if args.selector_validate:
        selector_validation = validate_selector_targets(merged_nkg, html, dom_ids)
        if selector_validation.get("available"):
            failed_total = selector_validation.get("summary", {}).get("failed_total", 0)
            print(f"[SELECTOR] failed: {failed_total}")

    if args.selector_repair_pass:
        failed_items = selector_validation.get("failed", []) if selector_validation.get("available") else []
        if failed_items:
            selector_repair["attempted"] = True
            to_fix = failed_items[: max(1, args.selector_repair_max)]
            selector_repair["requested_ids"] = len(to_fix)

            try:
                if backend == "remote":
                    repair_data = remote_repair_selectors(
                        server_url=args.remote_server_url,
                        api_token=args.remote_api_token,
                        filename=filename,
                        html_content=html,
                        page_url=page_url,
                        page_title=page_title,
                        elements_to_fix=to_fix,
                        preferred_model=args.model,
                        timeout_seconds=args.timeout,
                        use_fallback=args.remote_use_fallback,
                    )
                else:
                    repair_prompt = build_selector_repair_prompt(
                        page_url=page_url,
                        page_title=page_title,
                        page_slug=page_slug,
                        failed_elements=to_fix,
                        existing_nkg=merged_nkg,
                        html=html,
                    )
                    repair_raw = ollama_chat(
                        ollama_url=args.ollama_url,
                        model=args.model,
                        system_prompt=SELECTOR_REPAIR_SYSTEM_PROMPT,
                        user_prompt=repair_prompt,
                        timeout_seconds=args.timeout,
                        temperature=args.temperature,
                        num_predict=args.num_predict,
                        use_json_mode=True,
                        ollama_token=args.ollama_token,
                    )
                    repair_data = extract_json_from_text(repair_raw)

                repairs = repair_data.get("elements", []) if isinstance(repair_data, dict) else []
                if not isinstance(repairs, list):
                    raise ValueError("Selector repair must return elements[] list")

                by_id = {
                    e.get("id"): e
                    for e in merged_nkg.get("elements", [])
                    if isinstance(e, dict) and e.get("id")
                }

                applied = 0
                for item in repairs:
                    if not isinstance(item, dict):
                        continue
                    element_id = str(item.get("id", "")).strip()
                    selector = str(item.get("selector", "")).strip()
                    if not element_id or not selector or element_id not in by_id:
                        continue
                    by_id[element_id]["selector"] = selector
                    applied += 1

                selector_repair["applied_updates"] = applied
                selector_validation = validate_selector_targets(merged_nkg, html, dom_ids)
                print(f"[SELECTOR] repair applied: {applied}")
            except Exception as exc:  # noqa: BLE001
                selector_repair["attempted"] = True
                selector_repair["error"] = str(exc)
                print(f"[SELECTOR] repair error: {exc}")

    # DRY-RUN MODE: return early with collected prompts
    if args.dry_run:
        return {
            "meta": {
                "mode": "dry_run",
                "purpose": "Validate prompts and chunk structure without calling LLM",
                "source_html": str(html_path).replace("\\", "/"),
                "filename": filename,
                "page_url": page_url,
                "page_title": page_title,
                "chunk_config": {
                    "chunk_chars": args.chunk_chars,
                    "overlap_chars": args.overlap_chars,
                    "total_chunks": len(chunks),
                },
            },
            "dom_info": {
                "total_dom_ids": len(dom_ids),
                "all_dom_ids": sorted(dom_ids),
            },
            "prompts": dry_run_prompts,
        }

    verification = compute_verification(merged_nkg, dom_ids, dom_id_lines)
    cypher_payload = build_cypher_payload(merged_nkg)

    result = {
        "meta": {
            "schema_version": "nkg_chunked_v1",
            "source_html": str(html_path).replace("\\", "/"),
            "filename": filename,
            "backend": backend,
            "model": args.model,
            "ollama_url": args.ollama_url,
            "remote_server_url": args.remote_server_url if backend == "remote" else "",
            "page_url": page_url,
            "page_title": page_title,
            "chunk_config": {
                "chunk_chars": args.chunk_chars,
                "overlap_chars": args.overlap_chars,
                "total_chunks": len(chunks),
            },
            "runtime_seconds": round(time.time() - started, 2),
        },
        "nkg": merged_nkg,
        "verification": verification,
        "selector_validation": selector_validation,
        "selector_repair": selector_repair,
        "chunk_reports": chunk_reports,
        "cypher_payload": cypher_payload,
    }

    return result


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Chunked HTML -> NKG JSON extractor for one page")
    parser.add_argument("--html", required=True, help="Path to one cleaned HTML file")
    parser.add_argument("--out", required=True, help="Output JSON path")
    parser.add_argument(
        "--log-file",
        default="",
        help="Optional log file path. When set, all runtime output is written to this file instead of terminal.",
    )

    parser.add_argument(
        "--backend",
        choices=["local", "remote"],
        default="local",
        help="Inference backend: 'local' calls Ollama /api/chat directly, 'remote' calls server.py endpoints",
    )
    parser.add_argument("--model", default=DEFAULT_MODEL, help=f"Ollama model (default: {DEFAULT_MODEL})")
    parser.add_argument("--ollama-url", default=DEFAULT_OLLAMA_URL, help="Ollama base URL")
    parser.add_argument(
        "--ollama-token",
        default=os.getenv("OLLAMA_PROXY_TOKEN", ""),
        help="Ollama proxy auth token (sent as X-API-Token header, for proxied servers)",
    )
    parser.add_argument(
        "--remote-server-url",
        default=os.getenv("NKG_REMOTE_SERVER_URL", DEFAULT_REMOTE_SERVER_URL),
        help="Remote server.py base URL (used when --backend remote)",
    )
    parser.add_argument(
        "--remote-api-token",
        default=os.getenv("NKG_REMOTE_API_TOKEN", DEFAULT_REMOTE_API_TOKEN),
        help="API token for remote server.py (used when --backend remote)",
    )
    parser.add_argument(
        "--remote-use-fallback",
        action="store_true",
        help="Allow remote server fallback model when preferred model fails",
    )
    parser.add_argument("--dry-run", action="store_true", help="Preview prompts without calling Ollama (for validation)")
    parser.add_argument(
        "--script-html",
        default="",
        help="Path to raw HTML file to extract inline scripts from (appended to each chunk for trigger context)",
    )
    parser.add_argument(
        "--script-context",
        default="",
        help="Path to HTML file for script extraction, or 'auto' to extract from --html file itself",
    )

    parser.add_argument("--page-url", default="", help="Override inferred page URL")
    parser.add_argument("--page-title", default="", help="Override detected page title")

    parser.add_argument("--chunk-chars", type=int, default=18000, help="Target max chars per chunk")
    parser.add_argument("--overlap-chars", type=int, default=1200, help="Overlap chars between chunks")

    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT, help="Per request timeout (seconds)")
    parser.add_argument("--temperature", type=float, default=0.1, help="Sampling temperature")
    parser.add_argument("--num-predict", type=int, default=4096, help="Max generated tokens")
    parser.add_argument(
        "--stream",
        action="store_true",
        help="Stream model output in real time (local backend, or remote backend if server supports /extract/stream)",
    )
    parser.add_argument(
        "--show-thinking",
        action="store_true",
        help="Request model thinking tokens during streaming when backend supports it",
    )
    parser.add_argument(
        "--parallel-chunks",
        action="store_true",
        help="Run chunk inference in parallel threads, then merge results in chunk order",
    )
    parser.add_argument(
        "--parallel-workers",
        type=int,
        default=4,
        help="Worker count for --parallel-chunks (default: 4)",
    )

    parser.add_argument(
        "--patch-missing",
        action="store_true",
        help="Run patch pass for missing DOM ids in each chunk, letting LLM include worthy elements and exclude noise",
    )
    parser.add_argument(
        "--one-shot-example",
        default="",
        help="Path to previous result JSON (or raw NKG JSON) to use as one-shot example",
    )
    parser.add_argument(
        "--global-reconcile-pass",
        action="store_true",
        help="Run one extra patch-only full-page reconciliation pass after all chunks to catch cross-boundary relations",
    )
    parser.add_argument(
        "--selector-validate",
        action="store_true",
        help="Validate each final selector against source HTML and report failed selectors",
    )
    parser.add_argument(
        "--selector-repair-pass",
        action="store_true",
        help="Run one targeted selector repair pass for failed selectors only",
    )
    parser.add_argument(
        "--selector-repair-max",
        type=int,
        default=120,
        help="Maximum failed selector items to send to repair pass",
    )
    parser.add_argument(
        "--export-nkg-only",
        default="",
        help="Optional path to export only the final nkg object for reuse as one-shot example",
    )

    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    def _run_and_report() -> None:
        result = run(args)

        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")

        if args.export_nkg_only and "nkg" in result:
            nkg_path = Path(args.export_nkg_only)
            nkg_path.parent.mkdir(parents=True, exist_ok=True)
            nkg_path.write_text(json.dumps(result["nkg"], ensure_ascii=False, indent=2), encoding="utf-8")

        print(f"Saved: {out_path}")
        if args.backend == "remote":
            print(f"Backend: remote ({args.remote_server_url})")
        else:
            print(f"Backend: local ({args.ollama_url})")

        if result["meta"].get("mode") == "dry_run":
            print(f"DRY-RUN: {result['meta']['chunk_config']['total_chunks']} chunks, {result['dom_info']['total_dom_ids']} DOM ids")
            print(f"First chunk prompt chars: {len(result['prompts'][0]['user_prompt']) if result['prompts'] else 0}")
            return

        verification = result["verification"]
        print(
            "DOM ID coverage: "
            f"{verification['dom_ids_in_nkg_total']}/{verification['dom_ids_total']} "
            f"({verification['coverage_percent']}%)"
        )
        if verification["missing_dom_ids"]:
            print(f"Missing DOM ids: {len(verification['missing_dom_ids'])}")
        else:
            print("All DOM ids are covered.")

    if args.log_file:
        log_path = Path(args.log_file)
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with log_path.open("a", encoding="utf-8") as log_fp, redirect_stdout(log_fp), redirect_stderr(log_fp):
            print(f"\n===== Run started: {time.strftime('%Y-%m-%d %H:%M:%S')} =====")
            print(f"Command: {' '.join(sys.argv)}")
            _run_and_report()
            print(f"===== Run finished: {time.strftime('%Y-%m-%d %H:%M:%S')} =====")
    else:
        _run_and_report()


if __name__ == "__main__":
    main()