import json
from pathlib import Path

notebook_path = Path('insert.ipynb')
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

for cell in nb['cells']:
    if cell['cell_type'] != 'code':
        continue
    source = "".join(cell['source'])

    # Fix enrich() — only update if needed
    if "def enrich(raw_params: dict) -> dict:" in source:
        cell['source'] = [
            "def enrich(raw_params: dict) -> dict:\n",
            "    \"\"\"\n",
            "    Transform NKG data (or legacy cypher_payload.params) into Neo4j-ready dicts.\n",
            "    Adds nkg_id = \"{page_id}/{element_id}\" to elements and all relationship refs.\n",
            "    Filters bad trigger targets to prevent ghost node creation.\n",
            "\n",
            "    The NKG JSON format does not have an explicit 'contains' array — every element\n",
            "    in the list IS contained by the page, so we derive it from the elements list.\n",
            "    \"\"\"\n",
            "    page_id = raw_params[\"page\"][\"id\"]\n",
            "\n",
            "    def nkg(elem_id: str) -> str:\n",
            "        return f\"{page_id}/{elem_id}\"\n",
            "\n",
            "    # Elements\n",
            "    elements = [\n",
            "        {\n",
            "            \"nkg_id\":   nkg(e[\"id\"]),\n",
            "            \"id\":       e[\"id\"],\n",
            "            \"page_id\":  page_id,\n",
            "            \"desc\":     e.get(\"desc\", \"\"),\n",
            "            \"type\":     e.get(\"type\", \"\"),\n",
            "            \"selector\": e.get(\"selector\", \"\"),\n",
            "            \"text\":     e.get(\"text\", \"\"),\n",
            "        }\n",
            "        for e in raw_params.get(\"elements\", [])\n",
            "    ]\n",
            "\n",
            "    # Build a set of valid element IDs for this page — used to filter triggers\n",
            "    valid_elem_ids = {e[\"id\"] for e in raw_params.get(\"elements\", []) if e.get(\"id\")}\n",
            "\n",
            "    # Page -> Element CONTAINS\n",
            "    # Old cypher_payload.params had an explicit 'contains' list.\n",
            "    # The new NKG format doesn't — every element in the list belongs to the page.\n",
            "    raw_contains = raw_params.get(\"contains\", [])\n",
            "    if raw_contains:\n",
            "        # Legacy path: explicit contains list with element_id keys\n",
            "        contains = [\n",
            "            {\"page_id\": page_id, \"nkg_id\": nkg(c[\"element_id\"])}\n",
            "            for c in raw_contains\n",
            "        ]\n",
            "    else:\n",
            "        # NKG path: derive contains from all elements\n",
            "        contains = [\n",
            "            {\"page_id\": page_id, \"nkg_id\": nkg(e[\"id\"])}\n",
            "            for e in raw_params.get(\"elements\", [])\n",
            "        ]\n",
            "\n",
            "    # Element -> Element CONTAINS\n",
            "    element_contains = [\n",
            "        {\n",
            "            \"parent_nkg_id\": nkg(c[\"parent_id\"]),\n",
            "            \"child_nkg_id\":  nkg(c[\"child_id\"]),\n",
            "        }\n",
            "        for c in raw_params.get(\"element_contains\", [])\n",
            "    ]\n",
            "\n",
            "    # TRIGGERS — split into element-type and page-type\n",
            "    elem_triggers = []\n",
            "    page_triggers = []\n",
            "    skipped_triggers = 0\n",
            "\n",
            "    for t in raw_params.get(\"triggers\", []):\n",
            "        from_id  = t.get(\"from\", \"\")\n",
            "        to_id    = t.get(\"to\", \"\")\n",
            "        to_type  = t.get(\"to_type\", \"\")\n",
            "\n",
            "        if not from_id or not to_id:\n",
            "            skipped_triggers += 1\n",
            "            continue\n",
            "\n",
            "        if to_type == \"element\":\n",
            "            if to_id not in valid_elem_ids:\n",
            "                skipped_triggers += 1\n",
            "                continue\n",
            "            elem_triggers.append({\n",
            "                \"from_nkg_id\": nkg(from_id),\n",
            "                \"to_nkg_id\":   nkg(to_id),\n",
            "            })\n",
            "\n",
            "        elif to_type == \"page\":\n",
            "            page_triggers.append({\n",
            "                \"from_nkg_id\": nkg(from_id),\n",
            "                \"to\":          to_id,\n",
            "            })\n",
            "\n",
            "        else:\n",
            "            skipped_triggers += 1\n",
            "\n",
            "    return {\n",
            "        \"page_id\":           page_id,\n",
            "        \"title\":             raw_params[\"page\"].get(\"title\", \"\"),\n",
            "        \"desc\":              raw_params[\"page\"].get(\"desc\", \"\"),\n",
            "        \"elements\":          elements,\n",
            "        \"contains\":          contains,\n",
            "        \"element_contains\":  element_contains,\n",
            "        \"elem_triggers\":     elem_triggers,\n",
            "        \"page_triggers\":     page_triggers,\n",
            "        \"skipped_triggers\":  skipped_triggers,\n",
            "    }\n",
            "\n",
            "print(\"enrich() ready.\")"
        ]
        print("Fixed enrich() — contains now derived from elements when not explicitly provided.")

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Notebook saved.")
